// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngqsbaihrhhwidrpzjgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ncXNiYWlocmhod2lkcnB6amd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMDA3NjksImV4cCI6MjA1Mjc3Njc2OX0.9shij1nAAP0QZdEAFNruH8MY0u6oCAmAVzMTLME-7lU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);